# Generated by Django 4.0.5 on 2022-09-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flow', models.CharField(blank=True, max_length=100)),
                ('wa_id', models.CharField(max_length=17, unique=True)),
                ('wa_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_id', models.CharField(blank=True, max_length=100)),
                ('curr', models.CharField(blank=True, max_length=100)),
                ('item_price', models.CharField(blank=True, max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('wa_id', models.CharField(max_length=18)),
                ('msg_id', models.CharField(max_length=110, unique=True)),
                ('msg', models.TextField(default='')),
                ('interactive_id', models.CharField(default='', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('msg_type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mime_type', models.CharField(default='', max_length=30)),
                ('media_id', models.CharField(default='', max_length=60)),
                ('img_path', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_idd', models.CharField(blank=True, max_length=100)),
                ('product_quantity', models.CharField(blank=True, max_length=100)),
                ('catalog_idd', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('item_pricee', models.CharField(blank=True, max_length=100)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.messages')),
            ],
        ),
    ]
