# Generated by Django 4.0.5 on 2022-09-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_masterproducts_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalordertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=17, unique=True)),
                ('wa_name', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=8)),
                ('Tracking_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='pincode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_idd', models.CharField(blank=True, max_length=100)),
                ('product_quantity', models.CharField(blank=True, max_length=100)),
                ('catalog_idd', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('item_pricee', models.CharField(blank=True, max_length=100)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.finalordertable')),
            ],
        ),
    ]
